/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDownloadsRouteImport } from './routes/_authenticated/downloads'
import { Route as AuthenticatedLikesRouteImport } from './routes/_authenticated/likes'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDownloadsRouteImport } from './routes/admin.downloads'
import { Route as AdminLikesRouteImport } from './routes/admin.likes'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminPurchasesRouteImport } from './routes/admin.purchases'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as PaymentCompleteRouteImport } from './routes/payment.complete'
import { Route as SoftwareIndexRouteImport } from './routes/software.index'
import { Route as SoftwareSlugRouteImport } from './routes/software.$slug'
import { Route as AdminSoftwareIndexRouteImport } from './routes/admin.software.index'
import { Route as AdminSoftwareNewRouteImport } from './routes/admin.software.new'
import { Route as AdminSoftwareIdIndexRouteImport } from './routes/admin.software.$id.index'
import { Route as AdminSoftwareIdVersionsRouteImport } from './routes/admin.software.$id.versions'
import { Route as ApiPaymentsMoncashNotificationRouteImport } from './routes/api.payments.moncash.notification'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDownloadsRoute = AuthenticatedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLikesRoute = AuthenticatedLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDownloadsRoute = AdminDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLikesRoute = AdminLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchasesRoute = AdminPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const PaymentCompleteRoute = PaymentCompleteRouteImport.update({
  id: '/payment/complete',
  path: '/payment/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareIndexRoute = SoftwareIndexRouteImport.update({
  id: '/software/',
  path: '/software/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareSlugRoute = SoftwareSlugRouteImport.update({
  id: '/software/$slug',
  path: '/software/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSoftwareIndexRoute = AdminSoftwareIndexRouteImport.update({
  id: '/software/',
  path: '/software/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSoftwareNewRoute = AdminSoftwareNewRouteImport.update({
  id: '/software/new',
  path: '/software/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSoftwareIdIndexRoute = AdminSoftwareIdIndexRouteImport.update({
  id: '/software/$id/',
  path: '/software/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSoftwareIdVersionsRoute = AdminSoftwareIdVersionsRouteImport.update({
  id: '/software/$id/versions',
  path: '/software/$id/versions',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPaymentsMoncashNotificationRoute =
  ApiPaymentsMoncashNotificationRouteImport.update({
    id: '/api/payments/moncash/notification',
    path: '/api/payments/moncash/notification',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/likes': typeof AuthenticatedLikesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/likes': typeof AdminLikesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/payment/complete': typeof PaymentCompleteRoute
  '/software/$slug': typeof SoftwareSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/software/': typeof SoftwareIndexRoute
  '/admin/software/new': typeof AdminSoftwareNewRoute
  '/admin/software/': typeof AdminSoftwareIndexRoute
  '/admin/software/$id/versions': typeof AdminSoftwareIdVersionsRoute
  '/api/payments/moncash/notification': typeof ApiPaymentsMoncashNotificationRoute
  '/admin/software/$id/': typeof AdminSoftwareIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/likes': typeof AuthenticatedLikesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/likes': typeof AdminLikesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/payment/complete': typeof PaymentCompleteRoute
  '/software/$slug': typeof SoftwareSlugRoute
  '/admin': typeof AdminIndexRoute
  '/software': typeof SoftwareIndexRoute
  '/admin/software/new': typeof AdminSoftwareNewRoute
  '/admin/software': typeof AdminSoftwareIndexRoute
  '/admin/software/$id/versions': typeof AdminSoftwareIdVersionsRoute
  '/api/payments/moncash/notification': typeof ApiPaymentsMoncashNotificationRoute
  '/admin/software/$id': typeof AdminSoftwareIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/downloads': typeof AuthenticatedDownloadsRoute
  '/_authenticated/likes': typeof AuthenticatedLikesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/likes': typeof AdminLikesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/payment/complete': typeof PaymentCompleteRoute
  '/software/$slug': typeof SoftwareSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/software/': typeof SoftwareIndexRoute
  '/admin/software/new': typeof AdminSoftwareNewRoute
  '/admin/software/': typeof AdminSoftwareIndexRoute
  '/admin/software/$id/versions': typeof AdminSoftwareIdVersionsRoute
  '/api/payments/moncash/notification': typeof ApiPaymentsMoncashNotificationRoute
  '/admin/software/$id/': typeof AdminSoftwareIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/downloads'
    | '/likes'
    | '/profile'
    | '/purchases'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/downloads'
    | '/admin/likes'
    | '/admin/messages'
    | '/admin/purchases'
    | '/admin/settings'
    | '/admin/users'
    | '/payment/complete'
    | '/software/$slug'
    | '/admin/'
    | '/software/'
    | '/admin/software/new'
    | '/admin/software/'
    | '/admin/software/$id/versions'
    | '/api/payments/moncash/notification'
    | '/admin/software/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/downloads'
    | '/likes'
    | '/profile'
    | '/purchases'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/downloads'
    | '/admin/likes'
    | '/admin/messages'
    | '/admin/purchases'
    | '/admin/settings'
    | '/admin/users'
    | '/payment/complete'
    | '/software/$slug'
    | '/admin'
    | '/software'
    | '/admin/software/new'
    | '/admin/software'
    | '/admin/software/$id/versions'
    | '/api/payments/moncash/notification'
    | '/admin/software/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/_authenticated/downloads'
    | '/_authenticated/likes'
    | '/_authenticated/profile'
    | '/_authenticated/purchases'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/downloads'
    | '/admin/likes'
    | '/admin/messages'
    | '/admin/purchases'
    | '/admin/settings'
    | '/admin/users'
    | '/payment/complete'
    | '/software/$slug'
    | '/admin/'
    | '/software/'
    | '/admin/software/new'
    | '/admin/software/'
    | '/admin/software/$id/versions'
    | '/api/payments/moncash/notification'
    | '/admin/software/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PaymentCompleteRoute: typeof PaymentCompleteRoute
  SoftwareSlugRoute: typeof SoftwareSlugRoute
  SoftwareIndexRoute: typeof SoftwareIndexRoute
  ApiPaymentsMoncashNotificationRoute: typeof ApiPaymentsMoncashNotificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/downloads': {
      id: '/_authenticated/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthenticatedDownloadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/likes': {
      id: '/_authenticated/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof AuthenticatedLikesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/downloads': {
      id: '/admin/downloads'
      path: '/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AdminDownloadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/likes': {
      id: '/admin/likes'
      path: '/likes'
      fullPath: '/admin/likes'
      preLoaderRoute: typeof AdminLikesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchases': {
      id: '/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminPurchasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/payment/complete': {
      id: '/payment/complete'
      path: '/payment/complete'
      fullPath: '/payment/complete'
      preLoaderRoute: typeof PaymentCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software/': {
      id: '/software/'
      path: '/software'
      fullPath: '/software/'
      preLoaderRoute: typeof SoftwareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software/$slug': {
      id: '/software/$slug'
      path: '/software/$slug'
      fullPath: '/software/$slug'
      preLoaderRoute: typeof SoftwareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/software/': {
      id: '/admin/software/'
      path: '/software'
      fullPath: '/admin/software/'
      preLoaderRoute: typeof AdminSoftwareIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/software/new': {
      id: '/admin/software/new'
      path: '/software/new'
      fullPath: '/admin/software/new'
      preLoaderRoute: typeof AdminSoftwareNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/software/$id/': {
      id: '/admin/software/$id/'
      path: '/software/$id'
      fullPath: '/admin/software/$id/'
      preLoaderRoute: typeof AdminSoftwareIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/software/$id/versions': {
      id: '/admin/software/$id/versions'
      path: '/software/$id/versions'
      fullPath: '/admin/software/$id/versions'
      preLoaderRoute: typeof AdminSoftwareIdVersionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/payments/moncash/notification': {
      id: '/api/payments/moncash/notification'
      path: '/api/payments/moncash/notification'
      fullPath: '/api/payments/moncash/notification'
      preLoaderRoute: typeof ApiPaymentsMoncashNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDownloadsRoute: typeof AuthenticatedDownloadsRoute
  AuthenticatedLikesRoute: typeof AuthenticatedLikesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDownloadsRoute: AuthenticatedDownloadsRoute,
  AuthenticatedLikesRoute: AuthenticatedLikesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDownloadsRoute: typeof AdminDownloadsRoute
  AdminLikesRoute: typeof AdminLikesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPurchasesRoute: typeof AdminPurchasesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSoftwareNewRoute: typeof AdminSoftwareNewRoute
  AdminSoftwareIndexRoute: typeof AdminSoftwareIndexRoute
  AdminSoftwareIdVersionsRoute: typeof AdminSoftwareIdVersionsRoute
  AdminSoftwareIdIndexRoute: typeof AdminSoftwareIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDownloadsRoute: AdminDownloadsRoute,
  AdminLikesRoute: AdminLikesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPurchasesRoute: AdminPurchasesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSoftwareNewRoute: AdminSoftwareNewRoute,
  AdminSoftwareIndexRoute: AdminSoftwareIndexRoute,
  AdminSoftwareIdVersionsRoute: AdminSoftwareIdVersionsRoute,
  AdminSoftwareIdIndexRoute: AdminSoftwareIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PaymentCompleteRoute: PaymentCompleteRoute,
  SoftwareSlugRoute: SoftwareSlugRoute,
  SoftwareIndexRoute: SoftwareIndexRoute,
  ApiPaymentsMoncashNotificationRoute: ApiPaymentsMoncashNotificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
